# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Faizan Ansari
title: Network System Administrator
email: f97aizan@gmail.com
website: https://5zan-code.github.io/resume-/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: FaizanA74080881
github_username:  5zan-code
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: 5zan-ansari
linkedin_username: faizan-ansari-
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Faizan and I'm a network and system administrator. As well as administrating systems I also have experience cloud computing and DevOps. Right now I'm working a Systems and Desktop Support Technician @ Linamar Corp.

  I am most skilled in: <mark>AWS</mark> and <mark>Gym</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/5zan-code
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I am at the stage of learning and I will keep grasping knowledge until I turn 63 years.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way of learning <mark>Linux</mark> I created my own home lab using <mark>CentOS</mark> DNS, Game, and Video streaming server.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Home Lab
        #link: boringcompany.com
        link_text: MyHomeLab
        sub_title: Network System Administrator
        caption: November 2021 - Present
        quote: >
          Creating our own home infrastructure make me feel proud and happy
        description: | # this will include new lines to allow paragraphs
            This allows my home users(Friends)'s computers talk to each other without knowing there IP Address.
    
    #layout2: list # Type of content section (list/text)
    content2:
      - layout: left
        title: Multi Tier Web Application
        link: www.iaiitsolutions.com/
        link_text: IAI IT Solutions 
        sub_title: DevOps System Administrator
        caption: November 2020 - 2023
        quote: >
          Deploying a website while leveraging cloud technologies and using automated tools makes my life easy.
        description: | # this will include new lines to allow paragraphs
            Using AWS cloud infrastructure and internal networking my team and I deployed and automate the process of website and patch updates.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Amity University 
        caption: 2016 - 2020
        sub_title: Bachelor of technology (Computer Science and Engineering)
        quote: >
          Amity University was established on 24 March 2005 through The Amity University Uttar Pradesh Act, 2005 (Act 11 of 2005) of the UP Vidhan Sabha by the Ritnand Balved Education Foundation.
        description: | # this will include new lines to allow paragraphs
          During my time at Amity, I have learned core knowledge of computers and it working (OS, Chipset architecture, Algorithms, Data Structure, and AI). I also participate many other cultural and sports events.

          I have realy enjoyed my 4 years of engineering, teach me a lot about technologies and life. 

    layout2: list # Type of content section (list/text)
    content2:
      - layout: left
        title: Conestoga College (Waterloo)
        caption: 2021 - 2022
        sub_title: Post Graduate Certification (Mobile Solution Development)
        quote: >
          The college was founded in 1967 as the Conestoga College of Applied Arts and Technology, one of many such institutions established in that time by the Ontario government to grant diplomas and certificates in career-related, skills-oriented programs. It was renamed in 2012 when the government extended the school's reach, namely to grant degrees in technology-based fields.
        description: | # this will include new lines to allow paragraphs
          During my time at Conestoga Collage, I have learned many new and advance knowledge of technologies, website framework, and system architecture. I also participate member and employee of Conestoga Student Association know as CSI (Conestoga Student Inc).

          Those year and half was really facinating for me. Learned new life-style, culture, and cooking. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and system engineering some of my other interests and hobbies are:
      - Gym
      - Gaming (PC and PS4)
      - 8 Ball Pool
      - Swimming

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
